* Misc Commands
** nmap -sP # Ping sweep
Starting Nmap 4.11 ( http://www.insecure.org/nmap/ ) at 2016-12-01 21:03 MST
Host 10.229.7.1 appears to be up.
Host 10.229.7.2 appears to be up.
MAC Address: 00:50:56:96:28:C4 (VMWare)
Host 10.229.7.253 appears to be up.
MAC Address: 00:50:56:96:00:7C (VMWare)
Nmap finished: <t_co> IP addresses (3 hosts up) scanned in 31.090 seconds


* Host 1
IP: 10.229.7.2 appears to be up.
MAC Address: 00:50:56:96:28:C4 (VMWare)
** nmap -O -v
Interesting ports on 10.229.7.2:
Not shown: 1675 filtered ports
PORT     STATE SERVICE
22/tcp   open  ssh
443/tcp  open  https
3389/tcp open  ms-term-serv
5900/tcp open  vnc
8080/tcp open  http-proxy
MAC Address: 00:50:56:96:28:C4 (VMWare)
Device type: general purpose
Running: Microsoft Windows 2003/.NET|NT/2K/XP
OS details: Microsoft Windows 2003 Server or XP SP2, Microsoft Windows 2000
SP4 or XP SP1
TCP Sequence Prediction: Class=truly random
                         Difficulty=9999999 (Good luck!)
                         IPID Sequence Generation: Incremental
** nmap -sV -O -v
Starting Nmap 4.11 ( http://www.insecure.org/nmap/ ) at 2016-12-01 21:17 MST
Initiating ARP Ping Scan against 10.229.7.2 [1 port] at 21:17
The ARP Ping Scan took 0.00s to scan 1 total hosts.
DNS resolution of 1 IPs took 13.00s.
Initiating SYN Stealth Scan against 10.229.7.2 [1680 ports] at 21:17
Discovered open port 3389/tcp on 10.229.7.2
Discovered open port 22/tcp on 10.229.7.2
Discovered open port 443/tcp on 10.229.7.2
SYN Stealth Scan Timing: About 34.21% done; ETC: 21:19 (0:00:57 remaining)
Discovered open port 8080/tcp on 10.229.7.2
Discovered open port 5900/tcp on 10.229.7.2
The SYN Stealth Scan took 64.32s to scan 1680 total ports.
Initiating service scan against 5 services on 10.229.7.2 at 21:18
The service scan took 12.23s to scan 5 services on 1 host.
Warning:  OS detection will be MUCH less reliable because we did not find at
least 1 open and 1 closed TCP port
For OSScan assuming port 22 is open, 42743 is closed, and neither are firewalled
Host 10.229.7.2 appears to be up ... good.
Interesting ports on 10.229.7.2:
Not shown: 1675 filtered ports
PORT     STATE SERVICE       VERSION
22/tcp   open  ssh            (protocol 2.0)
443/tcp  open  ssl/http      Apache httpd 2.0.65 ((Win32) mod_ssl/2.0.65 OpenSSL/0.9.8y mod_auth_sspi/1.0.4)
3389/tcp open  microsoft-rdp Microsoft Terminal Service
5900/tcp open  vnc           VNC (protocol 3.3)
8080/tcp open  http          Apache httpd 2.0.65 ((Win32) mod_ssl/2.0.65 OpenSSL/0.9.8y mod_auth_sspi/1.0.4)
1 service unrecognized despite returning data. If you know the
service/version, please submit the following fingerprint at
http://www.insecure.org/cgi-bin/servicefp-submit.cgi : 
SF-Port22-TCP:V=4.11%I=7%D=12/1%Time=5840F634%P=i486-slackware-linux-gnu%r
SF:(NULL,15,"SSH-2\.0-OpenSSH_5\.6\r\n");
MAC Address: 00:50:56:96:28:C4 (VMWare)
Device type: general purpose
Running: IBM AIX 4.X, Microsoft Windows 2003/.NET|NT/2K/XP
OS details: IBM AIX 4.3.2.0-4.3.3.0 on an IBM RS/*, Microsoft Windows 2003 Server or XP SP2, Microsoft Windows XP SP2
TCP Sequence Prediction: Class=truly random
                         Difficulty=9999999 (Good luck!)
                         IPID Sequence Generation: Incremental
                         Service Info: OS: Windows
                         
                         Nmap finished: 1 IP address (1 host up) scanned in
                         91.553 seconds

* Host 2
IP: 10.229.7.253 appears to be up.
MAC Address: 00:50:56:96:00:7C (VMWare)
** nmap -O -v
All 1680 scanned ports on 10.229.7.253 are filtered
MAC Address: 00:50:56:96:00:7C (VMWare)
Too many fingerprints match this host to give specific OS details
TCP/IP fingerprint:
SInfo(V=4.11%P=i486-slackware-linux-gnu%D=12/1%Tm=5840EFD8%O=-1%C=-1%M=005056)
T5(Resp=N)
T6(Resp=N)
T7(Resp=N)
PU(Resp=N)


* Sources
http://www.computerworld.com/article/2761930/it-management/unix-how-to--using-nmap-to-map-your-network.html

